language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
before_install:
- echo $LANG
- echo $LC_ALL
script: cmake CMakeLists.txt
after_success:
- cd gtest/tests
- run_libdwgx_tests
branches:
  only:
  - master
  - "/^v\\d+\\./"
notifications:
  email: false
  irc:
    template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
env:
  global:
  - LANG="en_US.UTF-8"
