language: cpp
sudo: required
dist: trusty
compiler:
- gcc
- clang
os:
- linux
before_install:
- echo $LANG
- echo $LC_ALL
script: cmake -DBUILD_TESTS=ON CMakeLists.txt
after_success:
- make -j4
- cd tests
- ./libopencad_tests
branches:
  only:
  - master
notifications:
  email: 191980@niuitmo.ru
  irc:
    template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
env:
  global:
  - LANG="en_US.UTF-8"
