language: cpp
sudo: required
dist: trusty
compiler:
- gcc
- clang
os:
- linux
before_install:
- echo $LANG
- echo $LC_ALL
script: cmake CMakeLists.txt
after_success:
- cd /home/travis/build/sandyre/libopencad
- make test
branches:
  only:
  - master
notifications:
  email: false
  irc:
    template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
env:
  global:
  - LANG="en_US.UTF-8"
